Made\Bundle\EventStoreBundle\Entity\EventLog:
    type: entity
    table: made_event_log
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventType:
            type: string
        json:
            type: text
        error:
            type: text
            nullable: true
        response:
            type: text
            nullable: true
        date:
            type: datetime
    lifecycleCallbacks: {  }
