services:
    event_store.family_created:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnFamilyCreated
        arguments:
            - '@made_filters.family'
            - '@made_event_store.writer'
            - '%eventstore_attributes_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: family_created }

    event_store.family_updated:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnFamilyUpdated
        arguments:
            - '@made_filters.family'
            - '@made_event_store.writer'
            - '%eventstore_attributes_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: family_updated }

    event_store.attribute_created:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnAttributeCreated
        arguments:
            - '@made_filters.attribute'
            - '@made_event_store.writer'
            - '%eventstore_attributes_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: attribute_created }

    event_store.attribute_updated:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnAttributeUpdated
        arguments:
            - '@made_filters.attribute'
            - '@made_event_store.writer'
            - '%eventstore_attributes_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: attribute_updated }

    event_store.attribute_deleted:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnAttributeDeleted
        arguments:
            - '@made_filters.attribute'
            - '@made_event_store.writer'
            - '%eventstore_attributes_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: attribute_deleted }

    event_store.attribute_group_created:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnAttributeGroupCreated
        arguments:
            - '@made_filters.attributegroup'
            - '@made_event_store.writer'
            - '%eventstore_attributes_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: attribute_group_created }

    event_store.attribute_group_updated:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnAttributeGroupUpdated
        arguments:
            - '@made_filters.attributegroup'
            - '@made_event_store.writer'
            - '%eventstore_attributes_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: attribute_group_updated }

    event_store.product_created:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnProductCreated
        arguments:
            - '@made_filters.product'
            - '@made_event_store.writer'
            - '%eventstore_product_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: product_created }

    event_store.product_updated:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnProductUpdated
        arguments:
            - '@made_filters.product'
            - '@made_event_store.writer'
            - '%eventstore_product_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: product_updated }

    event_store.asset_created:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnAssetCreate
        arguments:
            - '@made_filters.asset'
            - '@made_event_store.writer'
            - '%eventstore_asset_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: asset_created }

    event_store.asset_updated:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnAssetUpdated
        arguments:
            - '@made_filters.asset'
            - '@made_event_store.writer'
            - '%eventstore_asset_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: asset_updated }

    event_store.asset_deleted:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnAssetDeleted
        arguments:
            - '@made_filters.asset'
            - '@made_event_store.writer'
            - '%eventstore_asset_stream_prefix%'
        tags:
            -  { name: event_store.event_listener, alias: asset_deleted }

    product_changed_status:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnProductChangedStatus
        arguments:
            - '@made_filters.productstatus'
            - '@made_event_store.writer'
            - '%eventstore_notifications_stream_prefix%'
        tags:
            - { name: kernel.event_listener, event: pim.event_store.product_status_changed, method: notify }

    product_completed:
        class: Made\Bundle\EventStoreBundle\EventstoreEvents\NotifyEventStoreOnProductCompleted
        arguments:
            - '@made_filters.productcompleted'
            - '@made_event_store.writer'
            - '%eventstore_notifications_stream_prefix%'
        tags:
            - { name: kernel.event_listener, event: pim.event_store.product_completed, method: notify }
